-- Add siteId column to all tables
ALTER TABLE file_storage ADD COLUMN IF NOT EXISTS site_id INTEGER DEFAULT 1 REFERENCES sites(id);
ALTER TABLE users ADD COLUMN IF NOT EXISTS site_id INTEGER DEFAULT 1 REFERENCES sites(id);
ALTER TABLE site_content ADD COLUMN IF NOT EXISTS site_id INTEGER DEFAULT 1 REFERENCES sites(id);
ALTER TABLE carousel_items ADD COLUMN IF NOT EXISTS site_id INTEGER DEFAULT 1 REFERENCES sites(id);
ALTER TABLE animals ADD COLUMN IF NOT EXISTS site_id INTEGER DEFAULT 1 REFERENCES sites(id);
ALTER TABLE products ADD COLUMN IF NOT EXISTS site_id INTEGER DEFAULT 1 REFERENCES sites(id);
ALTER TABLE dogs_hero ADD COLUMN IF NOT EXISTS site_id INTEGER DEFAULT 1 REFERENCES sites(id);
ALTER TABLE dogs ADD COLUMN IF NOT EXISTS site_id INTEGER DEFAULT 1 REFERENCES sites(id);
ALTER TABLE litters ADD COLUMN IF NOT EXISTS site_id INTEGER DEFAULT 1 REFERENCES sites(id);
ALTER TABLE principles ADD COLUMN IF NOT EXISTS site_id INTEGER DEFAULT 1 REFERENCES sites(id);
ALTER TABLE contact_info ADD COLUMN IF NOT EXISTS site_id INTEGER DEFAULT 1 REFERENCES sites(id);
ALTER TABLE goats ADD COLUMN IF NOT EXISTS site_id INTEGER DEFAULT 1 REFERENCES sites(id);
ALTER TABLE goat_litters ADD COLUMN IF NOT EXISTS site_id INTEGER DEFAULT 1 REFERENCES sites(id);
ALTER TABLE market_sections ADD COLUMN IF NOT EXISTS site_id INTEGER DEFAULT 1 REFERENCES sites(id);
ALTER TABLE market_schedules ADD COLUMN IF NOT EXISTS site_id INTEGER DEFAULT 1 REFERENCES sites(id);
ALTER TABLE litter_interest_signups ADD COLUMN IF NOT EXISTS site_id INTEGER DEFAULT 1 REFERENCES sites(id);

-- Update unique constraint on site_content to include siteId
ALTER TABLE site_content DROP CONSTRAINT IF EXISTS site_content_key_key;
ALTER TABLE site_content ADD CONSTRAINT site_content_key_site_id_key UNIQUE (key, site_id);